server:
  port: 8282
  servlet:
    context-path: /pizzeria

#by default log level is INFO
logging.level.org.springframework: DEBUG
#logging.level.com.vietle.angularecommercebackend=DEBUG
logging.level.com.vietle.angularecommercebackend: INFO

#jwt config
#valid for 15 minutes
security.jwt.token.expire-length: 900000
#900000 #15minutes


springdoc.api-docs.path: /api-docs
#management.endpoints.web.exposure.include=*

#custom table and column naming strategy
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: com.vietle.pizzeria.config.CustomDatabaseIdentifierNamingStrategy